[package]
name = "bob-nvim"
version = "1.2.1"
description = "A version manager for neovim"
license = "MIT"
readme = "README.md"
repository = "https://github.com/MordechaiHadad/bob"
edition = "2021"
exclude = ["resources/", "*.norg", "cliff.toml", ".github"] # Shame can't include target specific
keywords = ["neovim", "version-manager"]
categories = ["command-line-utilities"]

[[bin]]
name = "bob"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls"] }
tokio = { version = "1.16.1", features = ["full"] }
anyhow = "1.0.52"
indicatif = "0.16.2"
futures-util = "0.3.14"
dirs = "4.0.0"
cfg-if = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
yansi = "0.5.1"

[target.'cfg(windows)'.dependencies]
zip = "0.5"
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
tar = "0.4"
flate2 = "1.0"

[profile.optimized]
inherits = "release"
opt-level = "z"
strip = true
lto = true
codegen-units = 1
