[package]
name = "bob"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["stream"] }
tokio = { version = "1.16.1", features = ["full"] }
anyhow = "1.0.52"
indicatif = "0.16.2"
futures-util = "0.3.14"
dirs = "4.0.0"
cfg-if = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
yansi = "0.5.1"

[target.'cfg(windows)'.dependencies]
zip = "0.5"
winreg = "0.10.1"

[target.'cfg(unix)'.dependencies]
tar = "0.4"
flate2 = "1.0"

[features]
openssl = ["reqwest/default"]
rustls = ["reqwest/rustls-tls"]

[profile.optimized]
inherits = "release"
opt-level = "z"
strip = true
